### PR TITLE
Watch the video section   .js #17

### PR DESCRIPTION
**Pull request by Aliux02**
Stiliaus truksta, funkcionalumas yra

### CODE REVIEW

**Comment by wycka0214** [comment]
- resolve cofflict
- tada dar prikibciau prie vieno  kol kas: kai paspaudi video play pradeda eiti video, o kai paspaudi **x** grysta y home page, bet video kazkur antram plane eina, tai galetu paspaudus **x **ir video stop playing in background. :)

**Comment by Aliux02** [comment]
> * resolve cofflict
> * tada dar prikibciau prie vieno  kol kas: kai paspaudi video play pradeda eiti video, o kai paspaudi **x** grysta y home page, bet video kazkur antram plane eina, tai galetu paspaudus **x **ir video stop playing in background. :)

net nepastebejau sito 😁 ok, bandysim sprest ;)

**Review by TechNaa — DISMISSED** [review]

**Review by wycka0214 — APPROVED** [review]
looks great  🚀👌

**Review by TechNaa — APPROVED** [review]

**Review by evelinao1 — APPROVED** [review]
Super 👌

**Pull request merged**
